version: '2'
services:
  nginx:
    build: ./docker/nginx
#    image: nginx 
    ports:
      - "${NGINX_PORT}:80"
      - "${SSH_PORT}:443"
      - "81:81"
    volumes:
      - ./docker/nginx:/etc/nginx
      - ${WORKSPACE}:/var/www
  php-fpm:
    build: ./docker/php
#    image: php:7.2.0-fpm-alpine3.7
    ports: 
      - "127.0.0.1:9002:9000"
    volumes:
      - ./www:/var/www
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=FZ123456
    volumes:
      - ./data/mysql:/var/lib/mysql
  redis:
    build: ./docker/redis
#    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
      - ./docker/redis:/etc/redis
